# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Plagge's Development Blog
email: plaggm@rpi.edu
description: > # this means to ignore newlines until "baseurl:"
  This page covers all of my work on neuromorphic hardware simulations,
  high performance computing, and general development stuff. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markplagge.github.io" # the base hostname & protocol for your site
twitter_username: sonicscrewdrvr 
github_username:  markplagge

# Build settings
markdown: kramdown
